default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: multi-tenant-development

test:
  <<: *default
  database: multi-tenant-test

staging:
  <<: *default
  database: multi-tenant-staging

production:
  <<: *default
  database: multi-tenant-prod
  pool: <%= ENV['MAX_THREADS'] || 25 %>
